workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "dev"'
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - when: never

variables:
  APP_NAME: tradcore
  APP_URL: tradcore-dth.vlibras.lavid.ufpb.br
  RELEASE_NAME: vlibras-translator-text-core



include:
  # 🔹 Standard template for dev branches
  - project: 'vlibras2019/DevOps'
    ref: main
    file: '/Default-App-Pipeline-VLibras.gitlab-ci.yml'

# Overriding the inherited container-build job's "artifacts" block
container-build:
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}"
    reports:
      dotenv: build*.env
    paths:
      - build*.env  # ❌ removing oci-export*/ for testing
    expire_in: 1 hour
