apiVersion: v2
name: tradcore
description: VLibras AI translation module.
maintainers:
  - name: Ministry of Management and Innovation in Public Services (Brazil)
    email: sgd@gestao.gov.br
type: application
version: 0.1.1
appVersion: "1.16.1"
keywords:
  - vlibras
  - backend
  - nodejs
  - redis
  - rabbitmq