apiVersion: v2
name: tradcore
description: Módulo de traducción por IA de VLibras.
maintainers:
  - name: Ministerio de la Gestión e Innovación en Servicios Públicos
    email: sgd@gestao.gov.br
type: application
version: 0.1.1
appVersion: "1.16.1"
keywords:
  - vlibras
  - backend
  - nodejs
  - redis
  - rabbitmq